/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MediaRecognitionRouteImport } from './routes/media-recognition'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioTeamRouteImport } from './routes/studio.team'
import { Route as StudioHistoryRouteImport } from './routes/studio.history'
import { Route as StudioAboutRouteImport } from './routes/studio.about'
import { Route as ProjectsCategoryRouteImport } from './routes/projects.$category'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as PracticeProcessRouteImport } from './routes/practice.process'
import { Route as PracticeJournalRouteImport } from './routes/practice.journal'
import { Route as PracticeHistoryRouteImport } from './routes/practice.history'
import { Route as MediaRecognitionSlugRouteImport } from './routes/media-recognition.$slug'
import { Route as PracticeJournalSlugRouteImport } from './routes/practice.journal.$slug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRecognitionRoute = MediaRecognitionRouteImport.update({
  id: '/media-recognition',
  path: '/media-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioTeamRoute = StudioTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudioRoute,
} as any)
const StudioHistoryRoute = StudioHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAboutRoute = StudioAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StudioRoute,
} as any)
const ProjectsCategoryRoute = ProjectsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeProcessRoute = PracticeProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeJournalRoute = PracticeJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeHistoryRoute = PracticeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PracticeRoute,
} as any)
const MediaRecognitionSlugRoute = MediaRecognitionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaRecognitionRoute,
} as any)
const PracticeJournalSlugRoute = PracticeJournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PracticeJournalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media-recognition': typeof MediaRecognitionRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/media-recognition/$slug': typeof MediaRecognitionSlugRoute
  '/practice/history': typeof PracticeHistoryRoute
  '/practice/journal': typeof PracticeJournalRouteWithChildren
  '/practice/process': typeof PracticeProcessRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/projects/$category': typeof ProjectsCategoryRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/history': typeof StudioHistoryRoute
  '/studio/team': typeof StudioTeamRoute
  '/practice/journal/$slug': typeof PracticeJournalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media-recognition': typeof MediaRecognitionRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/media-recognition/$slug': typeof MediaRecognitionSlugRoute
  '/practice/history': typeof PracticeHistoryRoute
  '/practice/journal': typeof PracticeJournalRouteWithChildren
  '/practice/process': typeof PracticeProcessRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/projects/$category': typeof ProjectsCategoryRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/history': typeof StudioHistoryRoute
  '/studio/team': typeof StudioTeamRoute
  '/practice/journal/$slug': typeof PracticeJournalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/contact': typeof ContactRoute
  '/media-recognition': typeof MediaRecognitionRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/media-recognition/$slug': typeof MediaRecognitionSlugRoute
  '/practice/history': typeof PracticeHistoryRoute
  '/practice/journal': typeof PracticeJournalRouteWithChildren
  '/practice/process': typeof PracticeProcessRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/projects/$category': typeof ProjectsCategoryRoute
  '/studio/about': typeof StudioAboutRoute
  '/studio/history': typeof StudioHistoryRoute
  '/studio/team': typeof StudioTeamRoute
  '/practice/journal/$slug': typeof PracticeJournalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/contact'
    | '/media-recognition'
    | '/practice'
    | '/projects'
    | '/studio'
    | '/media-recognition/$slug'
    | '/practice/history'
    | '/practice/journal'
    | '/practice/process'
    | '/project/$slug'
    | '/projects/$category'
    | '/studio/about'
    | '/studio/history'
    | '/studio/team'
    | '/practice/journal/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/contact'
    | '/media-recognition'
    | '/practice'
    | '/projects'
    | '/studio'
    | '/media-recognition/$slug'
    | '/practice/history'
    | '/practice/journal'
    | '/practice/process'
    | '/project/$slug'
    | '/projects/$category'
    | '/studio/about'
    | '/studio/history'
    | '/studio/team'
    | '/practice/journal/$slug'
  id:
    | '__root__'
    | '/'
    | '/awards'
    | '/contact'
    | '/media-recognition'
    | '/practice'
    | '/projects'
    | '/studio'
    | '/media-recognition/$slug'
    | '/practice/history'
    | '/practice/journal'
    | '/practice/process'
    | '/project/$slug'
    | '/projects/$category'
    | '/studio/about'
    | '/studio/history'
    | '/studio/team'
    | '/practice/journal/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwardsRoute: typeof AwardsRoute
  ContactRoute: typeof ContactRoute
  MediaRecognitionRoute: typeof MediaRecognitionRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-recognition': {
      id: '/media-recognition'
      path: '/media-recognition'
      fullPath: '/media-recognition'
      preLoaderRoute: typeof MediaRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/team': {
      id: '/studio/team'
      path: '/team'
      fullPath: '/studio/team'
      preLoaderRoute: typeof StudioTeamRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/history': {
      id: '/studio/history'
      path: '/history'
      fullPath: '/studio/history'
      preLoaderRoute: typeof StudioHistoryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/about': {
      id: '/studio/about'
      path: '/about'
      fullPath: '/studio/about'
      preLoaderRoute: typeof StudioAboutRouteImport
      parentRoute: typeof StudioRoute
    }
    '/projects/$category': {
      id: '/projects/$category'
      path: '/$category'
      fullPath: '/projects/$category'
      preLoaderRoute: typeof ProjectsCategoryRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/process': {
      id: '/practice/process'
      path: '/process'
      fullPath: '/practice/process'
      preLoaderRoute: typeof PracticeProcessRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/journal': {
      id: '/practice/journal'
      path: '/journal'
      fullPath: '/practice/journal'
      preLoaderRoute: typeof PracticeJournalRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/history': {
      id: '/practice/history'
      path: '/history'
      fullPath: '/practice/history'
      preLoaderRoute: typeof PracticeHistoryRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/media-recognition/$slug': {
      id: '/media-recognition/$slug'
      path: '/$slug'
      fullPath: '/media-recognition/$slug'
      preLoaderRoute: typeof MediaRecognitionSlugRouteImport
      parentRoute: typeof MediaRecognitionRoute
    }
    '/practice/journal/$slug': {
      id: '/practice/journal/$slug'
      path: '/$slug'
      fullPath: '/practice/journal/$slug'
      preLoaderRoute: typeof PracticeJournalSlugRouteImport
      parentRoute: typeof PracticeJournalRoute
    }
  }
}

interface MediaRecognitionRouteChildren {
  MediaRecognitionSlugRoute: typeof MediaRecognitionSlugRoute
}

const MediaRecognitionRouteChildren: MediaRecognitionRouteChildren = {
  MediaRecognitionSlugRoute: MediaRecognitionSlugRoute,
}

const MediaRecognitionRouteWithChildren =
  MediaRecognitionRoute._addFileChildren(MediaRecognitionRouteChildren)

interface PracticeJournalRouteChildren {
  PracticeJournalSlugRoute: typeof PracticeJournalSlugRoute
}

const PracticeJournalRouteChildren: PracticeJournalRouteChildren = {
  PracticeJournalSlugRoute: PracticeJournalSlugRoute,
}

const PracticeJournalRouteWithChildren = PracticeJournalRoute._addFileChildren(
  PracticeJournalRouteChildren,
)

interface PracticeRouteChildren {
  PracticeHistoryRoute: typeof PracticeHistoryRoute
  PracticeJournalRoute: typeof PracticeJournalRouteWithChildren
  PracticeProcessRoute: typeof PracticeProcessRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeHistoryRoute: PracticeHistoryRoute,
  PracticeJournalRoute: PracticeJournalRouteWithChildren,
  PracticeProcessRoute: PracticeProcessRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsCategoryRoute: typeof ProjectsCategoryRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsCategoryRoute: ProjectsCategoryRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface StudioRouteChildren {
  StudioAboutRoute: typeof StudioAboutRoute
  StudioHistoryRoute: typeof StudioHistoryRoute
  StudioTeamRoute: typeof StudioTeamRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAboutRoute: StudioAboutRoute,
  StudioHistoryRoute: StudioHistoryRoute,
  StudioTeamRoute: StudioTeamRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwardsRoute: AwardsRoute,
  ContactRoute: ContactRoute,
  MediaRecognitionRoute: MediaRecognitionRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
